[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build -w packages/shared && npm run build -w apps/web"

[deploy]
startCommand = "npm run start -w apps/web"
restartPolicyType = "on_failure"
