import { Router } from "express";
import * as c from "../controllers/admin.js";

const router = Router();
router.get("/products", c.listProducts);
router.post("/products", c.createProduct);
router.put("/products/:id", c.updateProduct);
router.delete("/products/:id", c.deleteProduct);
router.get("/areas", c.listAreas);
router.post("/areas", c.createArea);
router.put("/areas/:id", c.updateArea);
router.delete("/areas/:id", c.deleteArea);
router.get("/statuses", c.listStatuses);
router.post("/statuses", c.createStatus);
router.put("/statuses/:id", c.updateStatus);
router.delete("/statuses/:id", c.deleteStatus);
router.get("/sources", c.listSources);
router.post("/sources", c.createSource);
router.put("/sources/:id", c.updateSource);
router.delete("/sources/:id", c.deleteSource);
router.get("/initiatives", c.listInitiatives);
router.post("/initiatives", c.createInitiative);
router.put("/initiatives/:id", c.updateInitiative);
router.delete("/initiatives/:id", c.deleteInitiative);
router.get("/releases", c.listReleases);
router.post("/releases", c.createRelease);
router.put("/releases/:id", c.updateRelease);
router.delete("/releases/:id", c.deleteRelease);
router.get("/config", c.getConfig);
router.put("/config", c.updateConfig);
router.get("/users", c.listUsers);
router.put("/users/:id/role", c.updateUserRole);
export default router;
